import NavBar from "@/components/NavBar";
import "./globals.css";
import Footer from "@/components/Footer";
import "bootstrap/dist/css/bootstrap.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ minHeight: "100vh" }}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
